# Generated by Django 5.1.5 on 2025-02-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0003_examoption_option'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamOption',
        ),
    ]
