# Generated by Django 5.1.5 on 2025-02-08 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0005_remove_question_question_text_question_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='rules',
        ),
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time_limit',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
