# Generated by Django 5.1.5 on 2025-02-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0006_remove_exam_rules_exam_date_exam_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='rules',
            field=models.TextField(default='no specific rules'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time_limit',
            field=models.IntegerField(),
        ),
    ]
