# Generated by Django 5.1.5 on 2025-03-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0009_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
