# Generated by Django 5.1.5 on 2025-03-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0012_remove_examresult_is_attempted_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
