# Generated by Django 5.1.5 on 2025-03-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0018_submission_submitted_at_alter_submission_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='recordings/'),
        ),
    ]
