# Generated by Django 5.1.5 on 2025-03-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0019_examresult_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='passing_grade',
            field=models.IntegerField(default=50),
        ),
    ]
