# Generated by Django 5.1.5 on 2025-03-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0020_exam_passing_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
