# Generated by Django 5.1.5 on 2025-03-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0021_examresult_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
