# Generated by Django 5.1.5 on 2025-03-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0022_alter_examresult_attempted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
