# Generated by Django 5.1.5 on 2025-03-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0025_alter_studentexam_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
