# Generated by Django 5.1.5 on 2025-03-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0027_exam_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='approval_status',
        ),
        migrations.AddField(
            model_name='exam',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
