# Generated by Django 5.1.5 on 2025-03-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0028_remove_exam_approval_status_exam_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='approved',
        ),
        migrations.AddField(
            model_name='exam',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
