# Generated by Django 5.1.5 on 2025-03-23 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0029_remove_exam_approved_exam_approval_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(verbose_name='Exam Date'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Custom Duration (optional)'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='passing_grade',
            field=models.IntegerField(default=50, verbose_name='Passing Grade (%)'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='rules',
            field=models.TextField(blank=True, null=True, verbose_name='Exam Rules (optional)'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Exam Subject'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time_limit',
            field=models.IntegerField(verbose_name='Time Limit (minutes)'),
        ),
    ]
