# Generated by Django 5.1.5 on 2025-03-24 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0030_alter_exam_options_exam_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exam',
            name='passing_grade',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='rules',
            field=models.TextField(default='No specific rules.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time_limit',
            field=models.IntegerField(),
        ),
    ]
