# Generated by Django 5.1.5 on 2025-03-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0032_remove_question_option_a_remove_question_option_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
