# Generated by Django 5.1.5 on 2025-03-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0033_exam_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
