# Generated by Django 5.1.7 on 2025-03-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0035_malpracticerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMalpractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField()),
                ('issue', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='malpracticerecord',
            old_name='issue',
            new_name='violation_type',
        ),
    ]
