# Generated by Django 5.1.7 on 2025-03-30 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0036_exammalpractice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='malpracticerecord',
            old_name='violation_type',
            new_name='issue',
        ),
    ]
