# Generated by Django 5.1.7 on 2025-03-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0037_rename_violation_type_malpracticerecord_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='malpractice_warnings',
            field=models.IntegerField(default=0),
        ),
    ]
